version: '3.7'

networks:
  kildeutgivelser:
    name: kildeutgivelser

volumes:
  tmp:

services:
  api:
    image: kildeutgivelser/api
    container_name: kildeutgivelser_api
    volumes:
      - /srv/stattholder_files:/var/stattholder-files/
      - ./api/config_templates:/config_templates
    restart: unless-stopped
    networks:
      kildeutgivelser:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - MYSQL_ROOT_PASSWORD
      - SECURITY_KEY
      - GIT_USERNAME
      - GIT_TOKEN
      - FLASK_DEBUG=1

  app:
    image: kildeutgivelser/web
    container_name: kildeutgivelser_http
    restart: unless-stopped
    depends_on:
      - api
    networks:
      kildeutgivelser:
    ports:
      - 80:8080
    volumes:
      - tmp:/tmp

  tei_tools:
    image: kildeutgivelser/tei_tools
    container_name: kildeutgivelser_tools
    restart: unless-stopped
    depends_on:
      - api
    networks:
      kildeutgivelser:
