version: '3.7'

networks:
  svn:
  kildeutgivelser:
    external: true

services:
  jetty:
    image: kildeutgivelser/jetty
    container_name: kildeutgivelser_jetty
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - /srv/svn:/opt/svn/
    networks:
      kildeutgivelser:

  svn:
    image: kildeutgivelser/svn
    container_name: kildeutgivelser_svn
    restart: unless-stopped
    depends_on:
      - jetty
    volumes:
      - /srv/svn:/opt/svn/
    networks:
      kildeutgivelser:
      svn:

  mysql:
    image: kildeutgivelser/mysql
    container_name: kildeutgivelser_mysql
    restart: unless-stopped
    networks:
      kildeutgivelser:
        aliases:
          - mysql-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - /srv/mysql_data:/var/lib/mysql
