version: '3'

networks:
  traefik:
    external: true

services:
  pgsql_server:
    container_name: pgsql_server
    image: kildeutgivelser/pgsql
    volumes:
      - ./pgsql_data:/var/lib/postgresql/data
    networks:
      traefik:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
        - 15432:5432
