version: '3'

networks:
  traefik:
    external: true

volumes:
  tmp:

services:
  api:
    image: kildeutgivelser/api
    volumes:
      - /srv/stattholder_files:/var/stattholder-files/
      - ./api/config_templates:/config_templates
      # - ./api_gitconfig:/home/uwsgi/.gitconfig
    restart: unless-stopped
    networks:
      traefik:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - SECURITY_KEY
      - GIT_USERNAME
      - GIT_TOKEN
      - FLASK_DEBUG=1

  app:
    image: kildeutgivelser/web
    restart: unless-stopped
    depends_on:
      - api
    # ports:
    #   - 2087:8080
    networks:
      traefik:
    volumes:
      - tmp:/tmp
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`kildeutgivelser.bratteng.com`)
      - traefik.http.routers.app.entrypoints=https
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=letsencrypt
      - traefik.http.routers.app.middlewares=cors@file

  tei_tools:
    image: kildeutgivelser/tei_tools
    depends_on:
      - api
    # ports:
    #   - 4200:4200
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.compress.compress=true
      - traefik.http.routers.tools.rule=Host(`kildeutgivelser.bratteng.com`)  && PathPrefix(`/tools`)
      - traefik.http.routers.tools.entrypoints=https
      - traefik.http.routers.tools.tls=true
      - traefik.http.routers.tools.tls.certresolver=letsencrypt
      - traefik.http.routers.tools.middlewares=cors@file,compress@docker
