FROM debian:buster-slim AS prepare
WORKDIR /var/www/html/public
COPY --from=slsfinland/digital_edition_web:beta /digital_edition_web/platforms/browser/www/ /var/www/html/public

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -xe \
	&& rm build/*.map \
	&& mv build/vendor.*.js build/vendor.js \
	&& mv build/main.*.js build/main.js

FROM ghcr.io/bratteng/nginx:mainline
WORKDIR /var/www/html/public

COPY --from=prepare /var/www/html/public /var/www/html/public

COPY nginx.conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY ./web/ /var/www/html/public/

EXPOSE 8080
