version: '3'

services:
  pgsql_server:
    container_name: pgsql_server
    image: postgres:10.11-alpine
    volumes:
      - ./digital_edition_db/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
      - ./db/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: SecretPassword
      POSTGRES_DB: digitaledition
    ports:
        - 15432:5432

  mysql_server:
    container_name: mysql_server
    image: mysql:8.0
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sahara-he-sune-slops-swishy-umble-cashew
      MYSQL_USER: topelius_notes
      MYSQL_PASSWORD: SecretPassword
      MYSQL_DATABASE: topelius_notes
    ports:
        - 13306:3306

  app:
    build:
      context: ./web/
    restart: unless-stopped
    ports:
      - "2087:80"
    volumes:
      - ./web/project_files_web/config.json:/var/www/config.json
      - ./web/project_files_web/index.html:/var/www/index.html
      - ./web/project_files_web/assets/custom_css:/var/www/assets/custom_css
      - ./web/project_files_web/assets/images:/var/www/assets/images
      - ./web/project_files_web/assets/artiklar:/var/www/assets/artiklar
      - ./web/project_files_web/assets/jpeg-files:/var/www/assets/jpeg-files

  api_proxy:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./api_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    ports:
      - "8000:80"

  api:
    build:
        context: ./digital_edition_api/
    volumes:
      - ./topelius_files:/var/topelius-files/

      # SSH keys for API to use may be mounted if needed
      #- /var/www/ssh/deploy_key:/home/uwsgi/.ssh/id_rsa

      # Config files need to be mounted
      - ./api_config:/app/sls_api/configs
      - ./db/users.db:/users.db
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=1

  tei_tools:
    build:
      context: ./digital_edition_tools/
    ports:
      - 4200:4200
    volumes:
      - ./digital_edition_tools/client:/app
