version: '3'

networks:
  # 172.31.240.0/20
  traefik:
    external: true

services:
  pgsql_server:
    container_name: pgsql_server
    image: postgres:10.11-alpine
    volumes:
      - ./digital_edition_db/db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
      - ./db/pgsql:/var/lib/postgresql/data
    networks:
      traefik:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: SecretPassword
      POSTGRES_DB: digitaledition
    ports:
        - 15432:5432

  mysql_server:
    container_name: mysql_server
    image: mysql:8.0
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      traefik:
    environment:
      MYSQL_ROOT_PASSWORD: sahara-he-sune-slops-swishy-umble-cashew
      MYSQL_USER: topelius_notes
      MYSQL_PASSWORD: SecretPassword
      MYSQL_DATABASE: topelius_notes
    ports:
        - 13306:3306

  app:
    build:
      context: ./web/
    restart: unless-stopped
    ports:
      - "2087:80"
    networks:
      traefik:
    volumes:
      - ./web/project_files_web/config.json:/var/www/config.json
      - ./web/project_files_web/index.html:/var/www/index.html
      - ./web/project_files_web/assets/custom_css:/var/www/assets/custom_css
      - ./web/project_files_web/assets/images:/var/www/assets/images
      - ./web/project_files_web/assets/artiklar:/var/www/assets/artiklar
      - ./web/project_files_web/assets/jpeg-files:/var/www/assets/jpeg-files
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`kildeutgivelser.bratteng.com`)
      - traefik.http.routers.app.entrypoints=https
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=letsencrypt
      - traefik.http.routers.api.middlewares=cors@docker

  api_proxy:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./api_proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    ports:
      - "8000:80"
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.kildeutgivelser.bratteng.com`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.routers.api.middlewares=cors@docker
      - traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PATCH,OPTIONS
      - traefik.http.middlewares.cors.headers.accessControlAllowOriginList=*
      - traefik.http.middlewares.cors.headers.accessControlAllowHeaders=Content-Type
      - traefik.http.middlewares.cors.headers.accessControlMaxAge=60

  api:
    build:
        context: ./digital_edition_api/
    volumes:
      - ./topelius_files:/var/topelius-files/

      # SSH keys for API to use may be mounted if needed
      #- /var/www/ssh/deploy_key:/home/uwsgi/.ssh/id_rsa

      # Config files need to be mounted
      - ./api_config:/app/sls_api/configs
      - ./api_gitconfig:/home/uwsgi/.gitconfig
      - ./db/users.db:/users.db
    restart: unless-stopped
    networks:
      traefik:
    environment:
      - FLASK_DEBUG=1

  tei_tools:
    build:
      context: ./tei_tools/
    ports:
      - 4200:4200
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.routers.tools.rule=Host(`tools.kildeutgivelser.bratteng.com`)
      - traefik.http.routers.tools.entrypoints=https
      - traefik.http.routers.tools.tls=true
      - traefik.http.routers.tools.tls.certresolver=letsencrypt
      - traefik.http.routers.api.middlewares=cors@docker
