version: '3'

networks:
  svn:
  traefik:
    external: true

volumes:
  tmp:

services:
  api:
    image: kildeutgivelser/api
    container_name: kildeutgivelser_api
    volumes:
      - /srv/stattholder_files:/var/stattholder-files/
      - ./api/config_templates:/config_templates
    restart: unless-stopped
    networks:
      traefik:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - SECURITY_KEY
      - GIT_USERNAME
      - GIT_TOKEN
      - FLASK_DEBUG=1

  app:
    image: kildeutgivelser/web
    container_name: kildeutgivelser_http
    restart: unless-stopped
    depends_on:
      - api
    networks:
      traefik:
    volumes:
      - tmp:/tmp
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`beta.kildeutgivelser.arkivverket.no`)
      - traefik.http.routers.app.entrypoints=http
      - traefik.http.routers.app.middlewares=cors@file

  tei_tools:
    image: kildeutgivelser/tei_tools
    container_name: kildeutgivelser_tools
    restart: unless-stopped
    depends_on:
      - api
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.compress.compress=true
      - traefik.http.routers.tools.rule=Host(`beta.kildeutgivelser.arkivverket.no`)  && PathPrefix(`/tools`)
      - traefik.http.routers.tools.entrypoints=http
      - traefik.http.routers.tools.middlewares=cors@file,compress@docker
