version: '3'

networks:
  # 172.31.240.0/20
  traefik:
    external: true

volumes:
  tmp:

services:
  pgsql_server:
    container_name: pgsql_server
    image: postgres:10.11-alpine
    volumes:
      - ./digital_edition_db/db_dump.sql:/docker-entrypoint-initdb.d/01-db_dump.sql
      - ./db/02-project.sql:/docker-entrypoint-initdb.d/02-project.sql
      - ./db/pgsql:/var/lib/postgresql/data
    networks:
      traefik:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
        - 15432:5432

  api:
    image: kildeutgivelser/api
    depends_on:
      - pgsql_server
    volumes:
      - ./stattholder_files:/var/stattholder-files/
      - ./api/config_templates:/config_templates
      # - ./
      # - ./api_gitconfig:/home/uwsgi/.gitconfig
    restart: unless-stopped
    networks:
      traefik:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - SECURITY_KEY
      - GIT_USERNAME
      - GIT_TOKEN
      - FLASK_DEBUG=1

  api_proxy:
    image: kildeutgivelser/api_proxy
    restart: unless-stopped
    depends_on:
      - api
    # ports:
    #   - 8080:8080
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.kildeutgivelser.bratteng.com`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.routers.api.middlewares=cors@file

  app:
    image: kildeutgivelser/web
    restart: unless-stopped
    depends_on:
      - api_proxy
    # ports:
    #   - 2087:8080
    networks:
      traefik:
    volumes:
      - tmp:/tmp
      - ./web/config.json:/var/www/html/public/config.json
      - ./web/index.html:/var/www/html/public/index.html
      - ./web/assets/custom_css:/var/www/html/public/assets/custom_css
      - ./web/assets/images:/var/www/html/public/assets/images
      - ./web/assets/artiklar:/var/www/html/public/assets/artiklar
      - ./web/assets/jpeg-files:/var/www/html/public/assets/jpeg-files
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`kildeutgivelser.bratteng.com`)
      - traefik.http.routers.app.entrypoints=https
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=letsencrypt
      - traefik.http.routers.app.middlewares=cors@file

  tei_tools:
    image: kildeutgivelser/tei_tools
    depends_on:
      - api_proxy
    # ports:
    #   - 4200:4200
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.compress.compress=true
      - traefik.http.routers.tools.rule=Host(`tools.kildeutgivelser.bratteng.com`)
      - traefik.http.routers.tools.entrypoints=https
      - traefik.http.routers.tools.tls=true
      - traefik.http.routers.tools.tls.certresolver=letsencrypt
      - traefik.http.routers.tools.middlewares=cors@file,compress@docker
