version: '3'


networks:
  traefik:
    external: true


services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - ./search/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      # ES_JAVA_OPTS: "-Xmx4096m -Xms2048m"
      ES_JAVA_OPTS: "-Xmx2048m -Xms2048m"
    networks:
      - traefik

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.6.1
    container_name: logstash
    restart: unless-stopped
    volumes:
      - ./search/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./search/pipeline:/usr/share/logstash/pipeline:ro
      - ./search/drivers:/app/drivers
      - /srv/stattholder_files/xml:/var/data/xml/stattholder_xml
    ports:
      - 5000:5000
      - 9600:9600
    environment:
      # LS_JAVA_OPTS: "-Xmx4096m -Xms2048m"
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_HOST:
      POSTGRES_PORT:
      LS_JAVA_OPTS: "-Xmx2048m -Xms2048m"
      LS_OPTS: "--auto-reload"
    depends_on:
      - elasticsearch
    networks:
      - traefik

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.6.1
    container_name: kibana
    volumes:
      - ./search/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - traefik
