version: '3'

networks:
  traefik:
    external: true

volumes:
  tmp:

services:
  api:
    image: kildeutgivelser/api
    depends_on:
      - pgsql_server
    volumes:
      - ./stattholder_files:/var/stattholder-files/
      - ./api/config_templates:/config_templates
      # - ./api_gitconfig:/home/uwsgi/.gitconfig
    restart: unless-stopped
    networks:
      traefik:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - SECURITY_KEY
      - GIT_USERNAME
      - GIT_TOKEN
      - FLASK_DEBUG=1

  api_proxy:
    image: kildeutgivelser/api_proxy
    restart: unless-stopped
    depends_on:
      - api
    # ports:
    #   - 8080:8080
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.kildeutgivelser.bratteng.com`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=letsencrypt
      - traefik.http.routers.api.middlewares=cors@file

  app:
    image: kildeutgivelser/web
    restart: unless-stopped
    depends_on:
      - api_proxy
    # ports:
    #   - 2087:8080
    networks:
      traefik:
    volumes:
      - tmp:/tmp
      - ./web/config.json:/var/www/html/public/config.json
      - ./web/index.html:/var/www/html/public/index.html
      - ./web/assets:/var/www/html/public/assets
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`kildeutgivelser.bratteng.com`)
      - traefik.http.routers.app.entrypoints=https
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=letsencrypt
      - traefik.http.routers.app.middlewares=cors@file

  tei_tools:
    image: kildeutgivelser/tei_tools
    depends_on:
      - api_proxy
    # ports:
    #   - 4200:4200
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.compress.compress=true
      - traefik.http.routers.tools.rule=Host(`tools.kildeutgivelser.bratteng.com`)
      - traefik.http.routers.tools.entrypoints=https
      - traefik.http.routers.tools.tls=true
      - traefik.http.routers.tools.tls.certresolver=letsencrypt
      - traefik.http.routers.tools.middlewares=cors@file,compress@docker
